spring:
  application:
    name: user-api
  datasource:
    # 不能使用root用户
    url: jdbc:mysql://106.14.239.125:3306/noc-security?characterEncoding=utf8
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # 生产不能这样使用
    generate-ddl: true
    show-sql: true
